name: Frontend CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: production-deployment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Debug GitHub Variables
        run: |
          echo "REPOSITORY=$GITHUB_REPOSITORY"
          echo "REF=$GITHUB_REF"

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::203221446879:role/github-actions-frontend-deploy-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://panacea-frontend-bucket-dev \
            --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1TGB5MSOEXZEP \
            --paths "/*"